### ISSUE TITLE
Exception: Error loading data from ../coco/val2017.txt: ../coco/val2017.txt does not exist

### ISSUE THREAD

**Issue by Edwardius** [WongKinYiu/ScaledYOLOv4#348]
Is there a specific link to the coco dataset that can be referenced? 

Current coco directory is:

images
   -test2017
   -train2017
   -unlabeled2017
   -val2017

annotations
   -captions_train2017.json       
   -image_info_test2017.json       
   -person_keypoints_train2017.json  
   -stuff_val2017.json
   -captions_val2017.json         
   -image_info_unlabeled2017.json  
   -person_keypoints_val2017.json    
   -stuff_val2017_pixelmaps.zip
   -deprecated-challenge2017     
   -instances_train2017.json      
   -stuff_train2017.json
   -image_info_test-dev2017.json 
   -instances_val2017.json      
   -stuff_train2017_pixelmaps.zip

**Comment by Edwardius** [comment]
Issue fixed BUT ENDED UP WITH A DIFFERENT PROBLEM, had to change to image directories in the coco.yaml file.
```
# train and val datasets (image directory or *.txt file with image paths)
train: ../coco/images/train2017  # 118k images
val: ../coco/images/val2017  # 5k images
test: ../coco/testdev2017.txt  # 20k images for submission to https://competitions.codalab.org/competitions/20794
```
Problem is, I end up with a new issue.
`
FileNotFoundError: [Errno 2] No such file or directory: '../coco/labels/val2017.cache'`

No clue how to solve this.

**Comment by mblak3** [comment]
You need to use the darknet style directories with images and labels. See this script: 
https://github.com/AlexeyAB/darknet/blob/master/scripts/get_coco2017.sh
Note that since you already have the images it seems, you can just use the drive link for the labels. 

You should have a directory structure of 
coco
-images
--train
--val
-labels
--train
--val

Once the program scans all of the images it will generate a train/val .cache file under the labels folder. 
Hope this helps
